### ISSUE TITLE
Can't start dispatch app due to hash_ring failing to start

### ISSUE THREAD

**Issue by myronmarston** [VoiceLayer/dispatch#1]
We are trying out your library but have run into a problem with the `hash-ring` library.  After adding it as a dependency to our project and running `mix deps.get` to fetch it, we get an error when we run `iex -S mix`:

```
➜  pubsub_test git:(hackathon) ✗ iex -S mix
Erlang/OTP 19 [erts-8.3] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

===> Compiling hash_ring
src/hash_ring.erl:283: Warning: function parse_list/1 is unused

Compiling 2 files (.ex)
Generated pubsub_test app

=INFO REPORT==== 8-May-2017::11:32:13 ===
    application: logger
    exited: stopped
    type: temporary
** (Mix) Could not start application dispatch: Dispatch.start(:normal, []) returned an error: shutdown: failed to start child: :hash_ring
    ** (EXIT) {:error, {:error, {:open_error, -10}}}
```

It looks like hash ring hasn't been compiled properly and I'm not sure how to make it do that.  Can you provide some instructions for how to get this working in your README?  Thanks!

**Comment by Gazler** [comment]
Ah, I raised an issue in Elixir for this at https://github.com/elixir-lang/elixir/issues/5830 - it is a breaking change in 1.4. This fix isn't too bad though:

          {:hash_ring, github: "voicelayer/hash-ring", manager: :rebar},

I fixed this in our project that uses dispatch, but forgot to update the README. I have updated it now. Thanks for bringing it to my attention. Please let me know if it works for you now.

**Comment by myronmarston** [comment]
We've actually decided to use phoenix_pubsub directly instead of relying on dispatch. Thanks for providing a fix, though!
